models/UserMeta.php
<?php

namespace app\models;

use app\models\master\Department;
use app\models\master\Section;

class UserMeta extends BaseModel
{
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function behaviors()
    {
        parent::initChild($this);
        return [];
    }

    public static function tableName()
    {
        return 'user_meta';
    }

    public static function primaryKey()
    {
        $primary_key = 'id';
        return array($primary_key);
    }

    public function attributeLabels()
    {
        $field = ['id', 'user_id', 'section_id', 'department_id', 'is_administration', 'is_supervisor', 'profile_picture', 'signature'];

        $attributeLabels = array();
        foreach ($field as $key) {
            $attributeLabels[$key] = $key;
        }

        return $attributeLabels;
    }

    public function getSection()
    {
        return $this->hasOne(Section::class, ['id' => 'section_id']);
    }

    public function getDepartment()
    {
        return $this->hasOne(Department::class, ['id' => 'department_id']);
    }

    public function getUser()
    {
        return $this->hasOne(User::class, ['id' => 'user_id']);
    }
}

views/proposal/create/add-detail.php
<?php use yii\helpers\Html; ?>

<?php if(empty($goodsServiceOption)) { ?>
    <div class="alert alert-danger">
        Terjadi kesalahan! Tidak ada goods/service tersedia untuk budget terpilih
    </div>
    <script>
        $(document).ready(function () {
            $('#form-budget-proposal-detail').find('*').prop('disabled', true);
        })
    </script>
<?php } ?>

<form action='' onsubmit='return false' id='form-budget-proposal-detail' class='form-horizontal col-lg-12 col-md-12'>
    <div id='result-add-budget-proposal-detail'></div>
    <div class='form-group'>
        <label class='col-lg-3 col-md-3 control-label'>Goods/Service</label>
        <div class='col-lg-9 col-md-9'>
            <?= Html::dropDownList('goods_service_id', null, $goodsServiceOption, ['required' => '', 'class' => 'form-control', 'onchange' => 'getGoodsServiceData()']) ?>
        </div>
    </div>
    <div class='form-group'>
        <label class='col-lg-3 col-md-3 control-label'>Quantity</label>
        <div class='col-lg-9 col-md-9'>
            <?= Html::input('number', 'quantity', null, ['class' => 'form-control', 'required' => '', 'placeholder' => 'Quantity']) ?>
        </div>
    </div>
    <div class='form-group'>
        <label class='col-lg-3 col-md-3 control-label'>Price Estimation</label>
        <div class='col-lg-9 col-md-9 form-control-static' id='td-price-estimation'></div>
    </div>
    <div class='form-group'>
        <label class='col-lg-3 col-md-3 control-label'>Currency</label>
        <div class='col-lg-9 col-md-9 form-control-static' id='td-currency'></div>
    </div>
    <div class='form-group'>
        <label class='col-lg-3 col-md-3 control-label'>Category</label>
        <div class='col-lg-9 col-md-9 form-control-static' id='td-category'></div>
    </div>
    <div class='form-group'>
        <label class='col-lg-3 col-md-3 control-label'>Carline</label>
        <div class='col-lg-9 col-md-9'>
            <?= Html::dropDownList('carline_id', null, $carlineOption, ['class' => 'form-control']) ?>
        </div>
    </div>
    <div class='form-group'>
        <label class='col-lg-3 col-md-3 control-label'>Comment</label>
        <div class='col-lg-9 col-md-9'>
            <?= Html::textarea('comment', null, ['class' => 'form-control', 'placeholder' => 'Comment']) ?>
        </div>
    </div>
    <div class='form-group'>
        <label class='col-lg-3 col-md-3 control-label'></label>
        <div class='col-lg-9 col-md-9'>
            <?= Html::input('submit', 'simpan', "Simpan", ['class' => 'btn btn-primary', 'id' => 'btn-save-proposal-detail']) ?>
        </div>
    </div>
    <?= Html::input('hidden', 'budget_id', $budget->id) ?>
    <?= Html::input('hidden', 'session_key', $sessionKey) ?>
</form>

<script>
    function getGoodsServiceData() {
        var gsCount = $('select[name=goods_service_id]').find('option');
        if(gsCount.length > 0){
            var data = getFormData('form-budget-proposal-detail');
            ajaxTransfer('proposal/create/get-goods-service-data', data, '#result-add-budget-proposal-detail');
        }
    }

    $(document).ready(function () {
        getGoodsServiceData();
        chosenConvert('select[name="carline_id"]');
        chosenConvert('select[name="goods_service_id"]');

        $('#form-budget-proposal-detail').submit(function () {
            var data = getFormData('form-budget-proposal-detail');
            ajaxTransfer('proposal/create/save-detail', data, '#result-add-budget-proposal-detail');
        });
    });

</script>

views/proposal/create/data-detail.php
<a onclick='addBudgetProposalDetail()' style='margin:10px 0' class='btn btn-primary'>
    <i class='fa fa-plus'></i> Add Budget Detail
</a>

<table class='table table-bordered table-striped'>
    <thead>
    <tr>
        <th>Goods/Service</th>
        <th>Carline</th>
        <th>Comment</th>
        <th>Quantity</th>
        <th>Price Estimation</th>
        <th>Sub Total</th>
        <th>Manage</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($data as $list) { ?>
        <tr class="nowrap">
            <td><?= $list->name ?></td>
            <td class='center'><?= $list->carline ?></td>
            <td class='center'><?= $list->comment ?></td>
            <td class='center'><?= $list->quantity ?></td>
            <td class='center'>
                <?= $list->price_estimation ?>
                <?php if(strlen($list->converted_price_estimation) > 0) { ?>
                    <br>[<?= $list->converted_price_estimation ?>]
                <?php } ?>
            </td>
            <td class='center'>
                <?= $list->sub_total ?>
                <?php if(strlen($list->converted_sub_total) > 0) { ?>
                    <br>[<?= $list->converted_sub_total?>]
                <?php } ?>
            </td>
            <td class='center'><a onclick='removeBudgetProposalDetail(<?= $list->id ?>)' class='btn btn-danger btn-xs'><i class='fa fa-times-circle'></i> Hapus</a></td>
        </tr>
    <?php } ?>
    </tbody>
    <tfoot>
    <tr>
        <th colspan='5'>Total</th>
        <th><b><?= $displayTotal ?></b></th>
        <th></th>
    </tr>
    </tfoot>
</table>

<script>
    function addBudgetProposalDetail() {
        var data = getFormData('form-budget-proposal');
        modalAlert('Add Budget Detail', '');
        ajaxTransfer('proposal/create/add-detail', data, '#modal-output');
    }

    function removeBudgetProposalDetail(id) {
        modalConfirm('Konfirmasi Tindakan', 'Apakah anda yakin akan menghapus budget detail?', function () {
            var data = {id: id, session_key: '<?= $sessionKey ?>'};
            ajaxTransfer('proposal/create/remove-detail', data, '#modal-output');
        });
    }
</script>

views/proposal/create/main.php
<?php

use yii\helpers\Html;

$this->title = 'Create New Budget Proposal';

?>
<?php if(empty($budgetOption)){ ?>
    <div class="alert alert-danger">
        Pembuatan proposal tidak dapat dilakukan dikarenakan tidak ada budget tersedia untuk periode mendatang
    </div>
    <script>
        $(document).ready(function () {
            $('#btn-save-proposal').prop('disabled', true)
        });
    </script>
<?php } ?>

<div id='budget-proposal-result'></div>
<ul class="nav nav-tabs">
    <li class="active">
        <a href="#tab-budget-info" data-toggle="tab">Budget Proposal Data</a>
    </li>
    <li>
        <a href="#tab-budget-detail" data-toggle="tab">Budget Proposal Detail</a>
    </li>
</ul>
<div class="tab-content bottom-margin">
    <div class="tab-pane active" id="tab-budget-info">
        <form onsubmit="return false;" id='form-budget-proposal' class='form-horizontal col-lg-12 col-md-12'>
            <div class='form-group'>
                <label class='col-lg-3 col-md-3 control-label'>Section</label>
                <div class='col-lg-9 col-md-9 form-control-static'><?= $activeUser->section->name ?></div>
            </div>
            <div class='form-group'>
                <label class='col-lg-3 col-md-3 control-label'>Budget Period</label>
                <div class='col-lg-9 col-md-9'>
                    <?= Html::dropdownList('budget_period_id', null, $budgetPeriodOption, ['class' => 'form-control', 'data-provide' => 'typeahead', 'required' => '']) ?>
                </div>
            </div>
            <div class='form-group'>
                <label class='col-lg-3 col-md-3 control-label'>Budget</label>
                <div class='col-lg-9 col-md-9'>
                    <div class='input-group m-bot15'>
                        <?= Html::dropdownList('budget_id', null, $budgetOption, ['class' => 'form-control', 'onchange' => 'clearProposalData()']) ?>
                        <span class='input-group-btn'>
						<button onclick='viewBudgetInfo()' class='btn btn-primary' type='button'><i
                                    class='fa fa-info-circle'></i>Info</button>
					</span>
                    </div>
                </div>
            </div>
            <div class='form-group'>
                <label class='col-lg-3 col-md-3 control-label'>Amount</label>
                <div class='col-lg-9 col-md-9'>
                    <div class="input-group m-bot15">
                        <span class="input-group-addon"><?= $baseCurrency->name ?></span>
                        <?= Html::input('number', 'amount', null, ['class' => 'form-control', 'required' => '', 'placeholder' => 'Amount']) ?>
                    </div>
                </div>
            </div>
            <div class='form-group'>
                <label class='col-lg-3 col-md-3 control-label'>Comment</label>
                <div class='col-lg-9 col-md-9'>
                    <?= Html::textarea('comment', null, ['class' => 'form-control', 'required' => 'required', 'placeholder' => 'Comment']) ?>
                </div>
            </div>
            <div class='form-group'>
                <label class='col-lg-3 col-md-3 control-label'></label>
                <div class='col-lg-9 col-md-9'>
                    <?= Html::input('submit', 'simpan', "Simpan", ['class' => 'btn btn-primary', 'id' => 'btn-save-proposal']) ?>
                </div>
            </div>
            <?= Html::hiddenInput('session_key', $sessionKey) ?>
        </form>
    </div>
    <div class="tab-pane" id="tab-budget-detail">
        <div id="output-budget-proposal-detail" class="col-lg-12 col-md-12"></div>
    </div>
</div>

<script>
    function clearProposalData() {
        var data = getFormData('form-budget-proposal');
        ajaxTransfer('proposal/create/clear-detail-data', data, '#output-budget-proposal-detail');
        initProposalConstraint();
    }

    function initProposalConstraint() {
        var data = getFormData('form-budget-proposal');
        ajaxTransfer('proposal/constraint/check-active-period', data, '#budget-proposal-result');
    }

    function viewBudgetInfo() {
        var budget_id = $('select[name="budget_id"]').val();
        modalAlert('Budget Information', '');
        ajaxTransfer('proposal/main/budget-info', {budget_id: budget_id}, '#modal-output');
    }
    
    function reloadBudgetProposalDetail() {
        var data = getFormData('form-budget-proposal');
        ajaxTransfer('proposal/create/reload-proposal-detail', data, '#output-budget-proposal-detail');
    }

    $('document').ready(function () {
        initProposalConstraint();
        reloadBudgetProposalDetail();
        chosenConvert('select[name="budget_id"]');

        $('#form-budget-proposal').submit(function () {
            var data = getFormData('form-budget-proposal');
            modalConfirm('Konfirmasi Tindakan', 'Apakah anda yakin data sudah benar? Data tidak dapat diubah setelah disubmit', function () {
                ajaxTransfer('proposal/create/save-data', data, '#modal-output');
            });
        });
    });
</script>