models/PoPayment.php
<?php

namespace app\models;

use app\models\master\BankDetail;
use app\models\master\PaymentMethod;

class PoPayment extends BaseModel
{
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function behaviors()
    {
        parent::initChild($this);
        return [];
    }

    public static function tableName()
    {
        return 'po_payment';
    }

    public static function primaryKey()
    {
        $primary_key = 'id';
        return array($primary_key);
    }

    public function attributeLabels()
    {
        $field = array('id', 'po_realization_id', 'bank_detail_id', 'payment_method_id', 'payment_document', 'comment', 'time');

        $attributeLabels = array();
        foreach ($field as $key) {
            $attributeLabels[$key] = $key;
        }

        return $attributeLabels;
    }

    public function __get($name)
    {
        switch ($name) {
            case 'document_url':
                return url(PO_PAYMENT_PATH . '/' . $this->payment_document);
        }
        return parent::__get($name); // TODO: Change the autogenerated stub
    }

    public function getRealization()
    {
        return $this->hasOne(PoRealization::class, ['id' => 'po_realization_id']);
    }

    public function getBankDetail()
    {
        return $this->hasOne(BankDetail::class, ['id' => 'bank_detail_id']);
    }

    public function getPaymentMethod()
    {
        return $this->hasOne(PaymentMethod::class, ['id' => 'payment_method_id']);
    }
}

models/PurchaseOrder.php
<?php

namespace app\models;

use app\helpers\PriceConverter;
use app\helpers\Tools;
use app\models\master\Franco;
use app\models\master\Supplier;
use app\models\master\Term;

class PurchaseOrder extends BaseModel
{
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function behaviors()
    {
        parent::initChild($this);
        return [];
    }

    public static function tableName()
    {
        return 'purchase_order';
    }

    public static function primaryKey()
    {
        $primary_key = 'id';
        return array($primary_key);
    }

    public function attributeLabels()
    {
        $field = ['id', 'no', 'date_submit', 'is_approved_by_lp_manager', 'approved_by_lp_manager_time', 'refax_path', 'term_id', 'franco_id', 'supplier_id', 'estimated_time_arival', 'actual_time_arival', 'is_with_down_payment', 'down_payment_amount', 'amount_estimation', 'amount_realization', 'comment', 'is_closed', 'is_rejected', 'is_confirmed', 'is_received', 'is_delivered', 'is_canceled', 'is_ontime', 'is_revision', 'is_checked', 'is_payment_complete'];

        $attributeLabels = array();
        foreach ($field as $key) {
            $attributeLabels[$key] = $key;
        }

        return $attributeLabels;
    }

    public function __get($name)
    {
        switch ($name) {
            case 'vat':
                $vat = 0;
                foreach ($this->purchaseRequisitionList as $pr) {
                    foreach ($pr->actualData as $actual) {
                        $vat += $actual->vat_amount;
                    }
                }
                return $vat;

            case 'rev_tax':
                $rev_tax = 0;
                foreach ($this->purchaseRequisitionList as $pr) {
                    foreach ($pr->actualData as $actual) {
                        $rev_tax += $actual->rev_tax_amount;
                    }
                }
                return $rev_tax;

            case 'vp_goods':
                return $this->getVpGoods();

            case 'vp_services':
                return $this->getVpServices();

            case 'display_amount_estimation':
                $currency = PriceConverter::getActiveBaseCurrency();
                return $currency->name . ' ' . currency_format($this->amount_estimation);

            case 'display_subtotal_amount_realization':
                return $this->getSubtotalAmountRealization(true, true);

            case 'display_amount_realization':
                $currency = PriceConverter::getActiveBaseCurrency();
                return $currency->name . ' ' . currency_format($this->amount_realization);

            case 'display_down_payment_amount':
                $currency = PriceConverter::getActiveBaseCurrency();
                return $currency->name . ' ' . currency_format($this->down_payment_amount);

            case 'display_rev_tax_amount':
                return $this->getRevTax(true, true);

            case 'display_vat_amount':
                return $this->getVAT(true, true);

            case 'display_vp_goods_amount':
                return $this->getVpGoods(true, true);

            case 'display_vp_services_amount':
                return $this->getVpServices(true, true);
        }

        return parent::__get($name);
    }

    private function getSubtotalAmountRealization($formatted = false, $converted = false)
    {
        $total = 0;
        foreach ($this->purchaseRequisitionList as $prList) {
            foreach ($prList->actualData as $actual) {
                $total += ($actual->quantity * $actual->price);
            }
        }

        $currency = PriceConverter::getActiveBaseCurrency();
        if ($converted) {
            $total = PriceConverter::convert($total, $currency->id);
        }

        if ($formatted) {
            return $currency->name . ' ' . currency_format($total);
        } else {
            return $total;
        }
    }

    private function getRevTax($formatted = false, $converted = false)
    {
        $total = 0;
        foreach ($this->purchaseRequisitionList as $prList) {
            foreach ($prList->actualData as $actual) {
                $total += $actual->rev_tax_amount;
            }
        }

        $currency = PriceConverter::getActiveBaseCurrency();
        if ($converted) {
            $total = PriceConverter::convert($total, $currency->id);
        }

        if ($formatted) {
            return $currency->name . ' ' . currency_format($total);
        } else {
            return $total;
        }
    }

    private function getVAT($formatted = false, $converted = false)
    {
        $total = 0;
        foreach ($this->purchaseRequisitionList as $prList) {
            foreach ($prList->actualData as $actual) {
                $total += $actual->vat_amount;
            }
        }

        $currency = PriceConverter::getActiveBaseCurrency();
        if ($converted) {
            $total = PriceConverter::convert($total, $currency->id);
        }

        if ($formatted) {
            return $currency->name . ' ' . currency_format($total);
        } else {
            return $total;
        }
    }

    private function getVpGoods($formatted = false, $converted = false)
    {
        $total = 0;
        foreach ($this->purchaseRequisitionList as $pr) {
            foreach ($pr->actualData as $actual) {
                $gs = $actual->goodsService;
                if ($gs->type == 'goods') {
                    $total += ($actual->quantity * $actual->price);
                }
            }
        }

        $currency = PriceConverter::getActiveBaseCurrency();
        if ($converted) {
            $total = PriceConverter::convert($total, $currency->id);
        }

        if ($formatted) {
            return $currency->name . ' ' . currency_format($total);
        } else {
            return $total;
        }
    }

    private function getVpServices($formatted = false, $converted = false)
    {
        $total = 0;
        foreach ($this->purchaseRequisitionList as $pr) {
            foreach ($pr->actualData as $actual) {
                $gs = $actual->goodsService;
                if ($gs->type == 'service') {
                    $total += ($actual->quantity * $actual->price);
                }
            }
        }

        $currency = PriceConverter::getActiveBaseCurrency();
        if ($converted) {
            $total = PriceConverter::convert($total, $currency->id);
        }

        if ($formatted) {
            return $currency->name . ' ' . currency_format($total);
        } else {
            return $total;
        }
    }

    public function getTerm()
    {
        return $this->hasOne(Term::class, ['id' => 'term_id']);
    }

    public function getFranco()
    {
        return $this->hasOne(Franco::class, ['id' => 'franco_id']);
    }

    public function getCode()
    {
        $no = str_pad($this->no, 3, '0', STR_PAD_LEFT);
        $section = 'PUR';
        $bulan = Tools::romanicNumber(date('n', strtotime($this->date_submit)));
        $tahun = date('y', strtotime($this->date_submit));
        return "PO-$no/$section-SAI/$bulan/$tahun";
    }

    public function getPurchaseRequisitionList()
    {
        return $this->hasMany(PoPrDetail::class, ['purchase_order_id' => 'id']);
    }

    public function getSupplier()
    {
        return $this->hasOne(Supplier::class, ['id' => 'supplier_id']);
    }

    public function getRealization()
    {
        return $this->hasMany(PoRealization::class, ['purchase_order_id' => 'id']);
    }

    public function getDisplayRealization()
    {
        $cond = [
            'is_rejected' => 0,
            'is_canceled' => 0
        ];

        if (get_session('include_rejected') === true) {
            unset($cond['is_rejected']);
        }

        if (get_session('only_rejected') === true) {
            $cond['is_rejected'] = 1;
        }

        if (get_session('include_canceled') === true) {
            unset($cond['is_canceled']);
        }

        if (get_session('only_canceled') === true) {
            $cond['is_canceled'] = 1;
        }

        return $this->getRealization()->where($cond)->all();
    }

    public function getRevision()
    {
        return $this->hasMany(PoRevision::class, ['purchase_order_id' => 'id']);
    }

    public function getDisplayRevision()
    {
        $cond = [
            'is_rejected' => 0,
            'is_canceled' => 0
        ];

        if (get_session('include_rejected') === true) {
            unset($cond['is_rejected']);
        }

        if (get_session('only_rejected') === true) {
            $cond['is_rejected'] = 1;
        }

        if (get_session('include_canceled') === true) {
            unset($cond['is_canceled']);
        }

        if (get_session('only_canceled') === true) {
            $cond['is_canceled'] = 1;
        }

        return $this->getRevision()->where($cond)->all();
    }

    public function paymentCompleteCheck()
    {
        $this->refresh();
        $data = $this->getRealization()->where([
            'is_approved_by_manager' => 1,
            'is_rejected' => 0,
            'is_canceled' => 0,
            'is_paid' => 0,
        ])->count();

        if ($data == 0) {
            self::updateAll(['is_payment_complete' => 1], ['id' => $this->id]);
        } else {
            self::updateAll(['is_payment_complete' => 0], ['id' => $this->id]);
        }
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);

        $this->refresh();
        if ($this->is_approved_by_lp_manager) {
            PurchaseOrder::updateAll(['is_checked' => 1], ['id' => $this->id]);
        }

        $date = date('Y-m', strtotime($this->date_submit));
        $num = PurchaseOrder::find()
            ->where(['between', 'date_submit', "$date-01", "$date-31"])
            ->andWhere(['<', 'id', $this->id])

models/UserMeta.php
<?php

namespace app\models;

use app\models\master\Department;
use app\models\master\Section;

class UserMeta extends BaseModel
{
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function behaviors()
    {
        parent::initChild($this);
        return [];
    }

    public static function tableName()
    {
        return 'user_meta';
    }

    public static function primaryKey()
    {
        $primary_key = 'id';
        return array($primary_key);
    }

    public function attributeLabels()
    {
        $field = ['id', 'user_id', 'section_id', 'department_id', 'is_administration', 'is_supervisor', 'profile_picture', 'signature'];

        $attributeLabels = array();
        foreach ($field as $key) {
            $attributeLabels[$key] = $key;
        }

        return $attributeLabels;
    }

    public function getSection()
    {
        return $this->hasOne(Section::class, ['id' => 'section_id']);
    }

    public function getDepartment()
    {
        return $this->hasOne(Department::class, ['id' => 'department_id']);
    }

    public function getUser()
    {
        return $this->hasOne(User::class, ['id' => 'user_id']);
    }
}

views/po/payment/create-new.php
<?php use yii\helpers\Html; ?>

<form id='form-payment' onsubmit="return false;" class='form-horizontal'>
    <div class='col-lg-12 col-md-12' id='result-payment-method'></div>
    <div class='form-group'>
        <label class='col-lg-3 col-md-3 control-label'>Bank</label>
        <div class='col-lg-9 col-md-9'>
            <?= Html::dropDownList('bank_id', null, $bankOption, ['class' => 'form-control', 'required' => '', 'onchange' => 'getBankDetail()']) ?>
        </div>
    </div>
    <div class='form-group'>
        <label class='col-lg-3 col-md-3 control-label'>Bank Detail</label>
        <div class='col-lg-9 col-md-9'>
            <?= Html::dropDownList('bank_detail_id', null, $bankDetailOption, ['class' => 'form-control', 'required' => '']) ?>
        </div>
    </div>
    <div class='form-group'>
        <label class='col-lg-3 col-md-3 control-label'>Payment Method</label>
        <div class='col-lg-9 col-md-9'>
            <?= Html::dropDownList('payment_method_id', null, $paymentMethodOption, ['class' => 'form-control']) ?>
        </div>
    </div>
    <div class='form-group'>
        <label class='col-lg-3 col-md-3 control-label'>Payment Document</label>
        <div class='col-lg-9 col-md-9'>
            <?= Html::input('file', 'payment_document', null, ['class' => 'form-control', 'required' => '']) ?>
            <div class='red' style='font-size: 90%;margin: 3px 0 0 0;'><i>Ekstensi yang diperbolehkan : pdf</i></div>
        </div>
    </div>
    <div class='form-group'>
        <label class='col-lg-3 col-md-3 control-label'>Comment</label>
        <div class='col-lg-9 col-md-9'>
            <?= Html::textarea('comment', null, ['class' => 'form-control', 'placeholder' => 'Comment']) ?>
        </div>
    </div>
    <div class='form-group'>
        <label class='col-lg-3 col-md-3 control-label'></label>
        <div class='col-lg-9 col-md-9'>
            <?= Html::input('submit', 'submit', 'Submit', ['class' => 'btn btn-primary']) ?>
        </div>
    </div>
    <?= Html::input('hidden', 'id', $data->id) ?>
</form>

<script>
    function getBankDetail() {
        var data = getFormData('form-payment');
        ajaxTransfer('po/payment/get-bank-detail', data, 'select[name="bank_detail_id"]');
    }

    $(document).ready(function () {
        $('#form-payment').submit(function () {
            if (confirm('Apakah anda yakin bahwa data sudah benar? Data tidak dapat diubah atau dihapus setelah disubmit!')){
                var data = getFormData('form-payment');
                ajaxTransfer('po/payment/save-data', data, '#result-payment-method');
            }
        });
    });

</script>

views/po/payment/detail.php
<form action='' method='post' class='form-horizontal'>
<div class='col-lg-12 col-md-12' id='result-payment-method'></div>
<div class='form-group'>
	<label class='col-lg-3 col-md-3 control-label'>Bank</label>
	<div class='col-lg-9 col-md-9 form-control-static'>
		<?= $payment->bankDetail->bank->name ?>
	</div>
</div>
<div class='form-group'>
	<label class='col-lg-3 col-md-3 control-label'>Account Number</label>
	<div class='col-lg-9 col-md-9 form-control-static'>
        <?= $payment->bankDetail->account_number ?>
	</div>
</div>
<div class='form-group'>
	<label class='col-lg-3 col-md-3 control-label'>Holder Name</label>
	<div class='col-lg-9 col-md-9 form-control-static'>
        <?= $payment->bankDetail->holder_name ?>
	</div>
</div>
<div class='form-group'>
	<label class='col-lg-3 col-md-3 control-label'>Payment Method</label>
	<div class='col-lg-9 col-md-9 form-control-static'>
        <?= $payment->paymentMethod->name ?>
	</div>
</div>
<div class='form-group'>
	<label class='col-lg-3 col-md-3 control-label'>Payment Document</label>
	<div class='col-lg-9 col-md-9 form-control-static'>
		<a href='<?= $payment->document_url ?>' target='_blank'>PAYMENT DOCUMENT</a>
	</div>
</div>
<div class='form-group'>
	<label class='col-lg-3 col-md-3 control-label'>Comment</label>
	<div class='col-lg-9 col-md-9 form-control-static'>
		<?= $payment->comment ?>
	</div>
</div>
</form>

views/po/payment/voucher-paying.php
<!DOCTYPE html>
<html>
<head>
    <title>Voucher Paying</title>
    <style>
        table {
            border-collapse: collapse;
            margin: 0 0 -1px 0;
        }

        table.border td {
            border: 1px solid;
            padding: 1px 2px;
        }

        table.no-border td {
            border: 0 none;
            padding: 1px 2px;
        }

        td.bg-signature {
            background-size: contain;
            background-position: center center;
            background-repeat: no-repeat;
        }
    </style>

</head>
<body>
<div style='display: inline-block;width: 170mm;position:relative;'>
    <div style='  color: red; border: 2px solid red; text-align: center; display: inline-block; padding: 15px 10px; font-size: 25px; position: absolute; right: 0; top: 0; font-weight: bold;opacity: 0.6;'>
        CONFIDENTIAL
    </div>
    <!-- header -->
    <div style='display: inline-block;width: 100%;'>
        <div style='display: block;float: left;margin: 0 20px 0 0;'><b style='font-size: 45px;line-height: 45px'>SAI</b>
        </div>
        <div style='float: left;text-align: center;'>
            <b style='font-size: 15px;margin: 0 0 -2px 0;display: block;'>PT.SURABAYA AUTOCOMP INDONESIA</b>
            <i style='display: block;'>Wiring Harness Manufacturer</i>
            <b style='font-size: 19px;display: block;'><u>VOUCHER PAYING</u></b>
        </div>
        <div style='float: left;margin: 0 0 0 20px;margin: 0 0 0 20px;width: 243px;overflow: hidden;'>
            <table style='border-collapse: collapse;'>
                <tr>
                    <td style='line-height: 18px;'>No.</td>
                    <td style='line-height: 18px;'>:</td>
                    <td style='line-height: 18px;'></td>
                </tr>
                <tr>
                    <td style='line-height: 18px;'>Date</td>
                    <td style='line-height: 18px;'>:</td>
                    <td style='line-height: 18px;'><?= date('d-M-y') ?></td>
                </tr>
                <tr>
                    <td style='line-height: 18px;'>Dept.</td>
                    <td style='line-height: 18px;'>:</td>
                    <td style='float: left;'><?= $activeUser->department->name ?></td>
                </tr>
            </table>
        </div>
    </div>
    <!-- /header -->

    <!-- main table -->
    <div style='display: inline-block;width: 100%;'>
        <!-- kolom atas -->
        <table class='border' style='width:100%'>
            <tr>
                <td>Paid To: <br><b><?= $purchaseOrder->supplier->name ?></b></td>
                <td>Amount Rp. : <span
                            style='border: 1px solid;padding: 5px 15px;font-weight: bold;'><?= $purchaseOrder->display_amount_realization ?></span>
                </td>
            </tr>
            <tr>
                <td>Date : <br><b><?= date('d-M-y', strtotime($data->deadline)) ?></b></td>
                <td>Say : <i><?= ucwords(terbilang($purchaseOrder->amount_realization)) ?></i></td>
            </tr>
        </table>
        <!-- /kolom atas -->

        <!-- kolom tengah -->
        <table class='border' style='width:100%'>
            <tr>
                <td style='width:50%;vertical-align: top;' rowspan='3'>
                    Payment For : <?= $data->supplier_invoice_number ?>
                    <table class='no-border' style='margin:5px 0 0 0; width:95%;'>
                        <tr>
                            <td>Material</td>
                            <td> :</td>
                            <td style='text-align:right;'><?= $purchaseOrder->display_vp_goods_amount ?></td>
                        </tr>
                        <tr>
                            <td>Jasa</td>
                            <td> :</td>
                            <td style='text-align:right;'><?= $purchaseOrder->display_vp_services_amount ?></td>
                        </tr>
                        <tr>
                            <td style='border-top:1px solid'>PPN</td>
                            <td style='border-top:1px solid'> :</td>
                            <td style='text-align:right;border-top:1px solid;'><?= $purchaseOrder->display_vat_amount ?></td>
                        </tr>
                        <tr>
                            <td>PPH</td>
                            <td> :</td>
                            <td style='text-align:right'><?= $purchaseOrder->display_rev_tax_amount ?></td>
                        </tr>
                        <tr>
                            <td style='border-top:1px solid'>Total</td>
                            <td style='border-top:1px solid'> :</td>
                            <td style='text-align:right;border-top:1px solid'><?= $purchaseOrder->display_amount_realization ?></td>
                        </tr>
                    </table>
                </td>
                <td style='width:50%; text-align:center;' colspan='4'>General Ledger</td>
            </tr>
            <tr>
                <td style='text-align:center;font-size: 12px;'>Profit Center</td>
                <td style='text-align:center;font-size: 12px;'>Account Code</td>
                <td style='text-align:center;font-size: 12px;'>Activity Center</td>
                <td style='text-align:center;font-size: 12px;'>Amount</td>
            </tr>
            <tr>
                <td style='height: 125px;'></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        </table>
        <!-- /kolom tengah -->

        <table class='border' style='width:100%'>
            <tr>
                <td colspan='5'>Paid Thru :</td>
            </tr>
            <tr>
                <td style='text-align:center;font-size: 12px;'>Cashier</td>
                <td style='text-align:center;font-size: 12px;'>Verified</td>
                <td style='text-align:center;font-size: 12px;'>Approved</td>
                <td style='text-align:center;font-size: 12px;'>Prepared</td>
                <td style='text-align:center;font-size: 12px;'>Received</td>
            </tr>
            <tr>
                <td style='height: 55px;'></td>

                <?php if (!is_null($signature['verified'])) { ?>
                    <td class="bg-signature"
                        style="background-image: url('<?= $signature['verified'] ?>');"></td>
                <?php } else { ?>
                    <td></td>
                <?php } ?>

                <?php if (!is_null($signature['approved'])) { ?>
                    <td class="bg-signature"
                        style="background-image: url('<?= $signature['approved'] ?>');"></td>
                <?php } else { ?>
                    <td></td>
                <?php } ?>

                <?php if (!is_null($signature['prepared'])) { ?>
                    <td class="bg-signature"
                        style="background-image: url('<?= $signature['prepared'] ?>');"></td>
                <?php } else { ?>
                    <td></td>
                <?php } ?>

                <td></td>
            </tr>
            <tr>
                <td colspan='5' style='text-align:right;border:0 none;'>FA-004-A</td>
            </tr>
        </table>
    </div>
    <!-- /main table -->
</div>
</body>
</html>