models/DpPrDetail.php
<?php

namespace app\models;

class DpPrDetail extends BaseModel
{
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function behaviors()
    {
        parent::initChild($this);
        return [];
    }

    public static function tableName()
    {
        return 'dp_pr_detail';
    }

    public static function primaryKey()
    {
        $primary_key = 'id';
        return array($primary_key);
    }

    public function attributeLabels()
    {
        $field = array('id', 'direct_purchase_id', 'purchase_requisition_id');

        $attributeLabels = array();
        foreach ($field as $key) {
            $attributeLabels[$key] = $key;
        }

        return $attributeLabels;
    }

    public function getDirectPurchase()
    {
        return $this->hasOne(DirectPurchase::class, ['id' => 'direct_purchase_id']);
    }

    public function getPurchaseRequisition()
    {
        return $this->hasOne(PurchaseRequisition::class, ['id' => 'purchase_requisition_id']);
    }

    public function getPurchaseRequisition_id()
    {
        return $this->hasOne(PurchaseRequisition::class, ['id' => 'purchase_requisition_id']);
    }

    public function getRealizationActual()
    {
        return $this->hasMany(DpRealizationActual::class, ['dp_pr_detail_id' => 'id']);
    }

    public function getRealizationPlan()
    {
        return $this->hasMany(DpRealizationPlan::class, ['dp_pr_detail_id' => 'id']);
    }
}

models/PurchaseOrder.php
<?php

namespace app\models;

use app\helpers\PriceConverter;
use app\helpers\Tools;
use app\models\master\Franco;
use app\models\master\Supplier;
use app\models\master\Term;

class PurchaseOrder extends BaseModel
{
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function behaviors()
    {
        parent::initChild($this);
        return [];
    }

    public static function tableName()
    {
        return 'purchase_order';
    }

    public static function primaryKey()
    {
        $primary_key = 'id';
        return array($primary_key);
    }

    public function attributeLabels()
    {
        $field = ['id', 'no', 'date_submit', 'is_approved_by_lp_manager', 'approved_by_lp_manager_time', 'refax_path', 'term_id', 'franco_id', 'supplier_id', 'estimated_time_arival', 'actual_time_arival', 'is_with_down_payment', 'down_payment_amount', 'amount_estimation', 'amount_realization', 'comment', 'is_closed', 'is_rejected', 'is_confirmed', 'is_received', 'is_delivered', 'is_canceled', 'is_ontime', 'is_revision', 'is_checked', 'is_payment_complete'];

        $attributeLabels = array();
        foreach ($field as $key) {
            $attributeLabels[$key] = $key;
        }

        return $attributeLabels;
    }

    public function __get($name)
    {
        switch ($name) {
            case 'vat':
                $vat = 0;
                foreach ($this->purchaseRequisitionList as $pr) {
                    foreach ($pr->actualData as $actual) {
                        $vat += $actual->vat_amount;
                    }
                }
                return $vat;

            case 'rev_tax':
                $rev_tax = 0;
                foreach ($this->purchaseRequisitionList as $pr) {
                    foreach ($pr->actualData as $actual) {
                        $rev_tax += $actual->rev_tax_amount;
                    }
                }
                return $rev_tax;

            case 'vp_goods':
                return $this->getVpGoods();

            case 'vp_services':
                return $this->getVpServices();

            case 'display_amount_estimation':
                $currency = PriceConverter::getActiveBaseCurrency();
                return $currency->name . ' ' . currency_format($this->amount_estimation);

            case 'display_subtotal_amount_realization':
                return $this->getSubtotalAmountRealization(true, true);

            case 'display_amount_realization':
                $currency = PriceConverter::getActiveBaseCurrency();
                return $currency->name . ' ' . currency_format($this->amount_realization);

            case 'display_down_payment_amount':
                $currency = PriceConverter::getActiveBaseCurrency();
                return $currency->name . ' ' . currency_format($this->down_payment_amount);

            case 'display_rev_tax_amount':
                return $this->getRevTax(true, true);

            case 'display_vat_amount':
                return $this->getVAT(true, true);

            case 'display_vp_goods_amount':
                return $this->getVpGoods(true, true);

            case 'display_vp_services_amount':
                return $this->getVpServices(true, true);
        }

        return parent::__get($name);
    }

    private function getSubtotalAmountRealization($formatted = false, $converted = false)
    {
        $total = 0;
        foreach ($this->purchaseRequisitionList as $prList) {
            foreach ($prList->actualData as $actual) {
                $total += ($actual->quantity * $actual->price);
            }
        }

        $currency = PriceConverter::getActiveBaseCurrency();
        if ($converted) {
            $total = PriceConverter::convert($total, $currency->id);
        }

        if ($formatted) {
            return $currency->name . ' ' . currency_format($total);
        } else {
            return $total;
        }
    }

    private function getRevTax($formatted = false, $converted = false)
    {
        $total = 0;
        foreach ($this->purchaseRequisitionList as $prList) {
            foreach ($prList->actualData as $actual) {
                $total += $actual->rev_tax_amount;
            }
        }

        $currency = PriceConverter::getActiveBaseCurrency();
        if ($converted) {
            $total = PriceConverter::convert($total, $currency->id);
        }

        if ($formatted) {
            return $currency->name . ' ' . currency_format($total);
        } else {
            return $total;
        }
    }

    private function getVAT($formatted = false, $converted = false)
    {
        $total = 0;
        foreach ($this->purchaseRequisitionList as $prList) {
            foreach ($prList->actualData as $actual) {
                $total += $actual->vat_amount;
            }
        }

        $currency = PriceConverter::getActiveBaseCurrency();
        if ($converted) {
            $total = PriceConverter::convert($total, $currency->id);
        }

        if ($formatted) {
            return $currency->name . ' ' . currency_format($total);
        } else {
            return $total;
        }
    }

    private function getVpGoods($formatted = false, $converted = false)
    {
        $total = 0;
        foreach ($this->purchaseRequisitionList as $pr) {
            foreach ($pr->actualData as $actual) {
                $gs = $actual->goodsService;
                if ($gs->type == 'goods') {
                    $total += ($actual->quantity * $actual->price);
                }
            }
        }

        $currency = PriceConverter::getActiveBaseCurrency();
        if ($converted) {
            $total = PriceConverter::convert($total, $currency->id);
        }

        if ($formatted) {
            return $currency->name . ' ' . currency_format($total);
        } else {
            return $total;
        }
    }

    private function getVpServices($formatted = false, $converted = false)
    {
        $total = 0;
        foreach ($this->purchaseRequisitionList as $pr) {
            foreach ($pr->actualData as $actual) {
                $gs = $actual->goodsService;
                if ($gs->type == 'service') {
                    $total += ($actual->quantity * $actual->price);
                }
            }
        }

        $currency = PriceConverter::getActiveBaseCurrency();
        if ($converted) {
            $total = PriceConverter::convert($total, $currency->id);
        }

        if ($formatted) {
            return $currency->name . ' ' . currency_format($total);
        } else {
            return $total;
        }
    }

    public function getTerm()
    {
        return $this->hasOne(Term::class, ['id' => 'term_id']);
    }

    public function getFranco()
    {
        return $this->hasOne(Franco::class, ['id' => 'franco_id']);
    }

    public function getCode()
    {
        $no = str_pad($this->no, 3, '0', STR_PAD_LEFT);
        $section = 'PUR';
        $bulan = Tools::romanicNumber(date('n', strtotime($this->date_submit)));
        $tahun = date('y', strtotime($this->date_submit));
        return "PO-$no/$section-SAI/$bulan/$tahun";
    }

    public function getPurchaseRequisitionList()
    {
        return $this->hasMany(PoPrDetail::class, ['purchase_order_id' => 'id']);
    }

    public function getSupplier()
    {
        return $this->hasOne(Supplier::class, ['id' => 'supplier_id']);
    }

    public function getRealization()
    {
        return $this->hasMany(PoRealization::class, ['purchase_order_id' => 'id']);
    }

    public function getDisplayRealization()
    {
        $cond = [
            'is_rejected' => 0,
            'is_canceled' => 0
        ];

        if (get_session('include_rejected') === true) {
            unset($cond['is_rejected']);
        }

        if (get_session('only_rejected') === true) {
            $cond['is_rejected'] = 1;
        }

        if (get_session('include_canceled') === true) {
            unset($cond['is_canceled']);
        }

        if (get_session('only_canceled') === true) {
            $cond['is_canceled'] = 1;
        }

        return $this->getRealization()->where($cond)->all();
    }

    public function getRevision()
    {
        return $this->hasMany(PoRevision::class, ['purchase_order_id' => 'id']);
    }

    public function getDisplayRevision()
    {
        $cond = [
            'is_rejected' => 0,
            'is_canceled' => 0
        ];

        if (get_session('include_rejected') === true) {
            unset($cond['is_rejected']);
        }

        if (get_session('only_rejected') === true) {
            $cond['is_rejected'] = 1;
        }

        if (get_session('include_canceled') === true) {
            unset($cond['is_canceled']);
        }

        if (get_session('only_canceled') === true) {
            $cond['is_canceled'] = 1;
        }

        return $this->getRevision()->where($cond)->all();
    }

    public function paymentCompleteCheck()
    {
        $this->refresh();
        $data = $this->getRealization()->where([
            'is_approved_by_manager' => 1,
            'is_rejected' => 0,
            'is_canceled' => 0,
            'is_paid' => 0,
        ])->count();

        if ($data == 0) {
            self::updateAll(['is_payment_complete' => 1], ['id' => $this->id]);
        } else {
            self::updateAll(['is_payment_complete' => 0], ['id' => $this->id]);
        }
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);

        $this->refresh();
        if ($this->is_approved_by_lp_manager) {
            PurchaseOrder::updateAll(['is_checked' => 1], ['id' => $this->id]);
        }

        $date = date('Y-m', strtotime($this->date_submit));
        $num = PurchaseOrder::find()
            ->where(['between', 'date_submit', "$date-01", "$date-31"])
            ->andWhere(['<', 'id', $this->id])

views/po/modify/index.php
<?php
$this->title = 'Purchase Order Revision';
?>

<ul class="nav nav-tabs">
    <li class="active"><a href="#tab-po-data" data-toggle="tab">PO Data</a></li>
    <li><a href="#tab-po-detail" data-toggle="tab">PO Actual</a></li>
</ul>
<div class="tab-content">
    <div class="tab-pane active" id="tab-po-data">
        <?php require 'po-data.php'; ?>
    </div>
    <div class="tab-pane" id="tab-po-detail">
        <?php require 'po-actual.php'; ?>
    </div>
</div>

views/po/modify/pending.php
<?php
$this->title = 'Pending PO Revision';
$data = isset($data) ? $data : [];
?>

<div class='div-datatable'>
<table class='display table table-bordered table-striped' id='tabel-data-master'>
<thead>
<tr>
	<th>PO ID</th>
	<th>Supplier</th>
	<th>Amount Estimation</th>
	<th>Amount Realization</th>
	<th>DP</th>
	<th>Manage</th>
</tr>
</thead>
<?php
foreach($data as $list){
	if($list->is_with_down_payment){
		$down_payment = "<i class='fa fa-check-circle fa-lg green'></i>";
	}
	else{
		$down_payment = "<i class='fa fa-times-circle fa-lg red'></i>";
	}
	
	echo "
	<tr>
		<td class='center'>".$list->code."</td>
		<td class='center'>".$list->supplier->name."</td>
		<td class='center'>".number_format($list->amount_estimation, 2, ',', '.')."</td>
		<td class='center'>".number_format($list->amount_realization, 2, ',', '.')."</td>
		<td class='center'>$down_payment</td>
		<td class='center'>
			<a class='btn btn-primary btn-xs' href='".url("po/main/detail/?id=$list->id")."' title='Detail Data'><i class='fa fa-eye'></i> Detail</a>
		</td>
	</tr>
	";
}
?>
</table>
</div>

<script>
$(document).ready(function(){
	convert_datatables('tabel-data-master');
});
</script>

<style>
.filter-manager *, .filter-dp *, .filter-dfm *, .filter-fm *, .filter-presdir *, .filter-fa *, .filter-select *{
display: none;
}
</style>

views/po/modify/po-actual.php
<?php use yii\helpers\Html; ?>

<div class="col-lg-12 col-md-12">
    <div id='temp-revision' style='margin:10px 0'></div>
    <form onsubmit='return false;' id='form-revision-detail'>
        <table class='table table-bordered table-striped'>
            <thead>
            <tr>
                <th>PR Code</th>
                <th>Goods/Service</th>
                <th>Carline</th>
                <th>Quantity</th>
                <th>Price Estimation</th>
                <th>Sub Total</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($data->purchaseRequisitionList as $poPr) { ?>
                <?php foreach ($poPr->actualData as $actual) { ?>
                    <?php $actualCurrency = $actual->goodsService->currency; ?>
                    <tr>
                        <td><?= $actual->purchaseRequisition->code ?></td>
                        <td><?= $actual->goodsService->name ?></td>
                        <td><?= $actual->carline->name ?></td>
                        <td class='center' style="padding:2px;">
                            <?php $min = $actual->received == 0 ? 1 : $actual->received; ?>
                            <?= Html::input('number', "quantity-" . $actual->id, $actual->quantity, ['min' => $min, 'max' => $actual->quantity, 'class' => 'form-control', 'required' => 'required']) ?>
                        </td>
                        <td class='center' style="padding:2px;">
                            <div class="input-group">
                                <span class="input-group-addon"><?= $actualCurrency->name ?></span>
                                <?php $maxPrice = $actual->price + (0.1 * $actual->price); ?>
                                <?php $minPrice = $actual->price - (0.1 * $actual->price); ?>
                                <?= Html::input('number', "price-" . $actual->id, $actual->price, ['min' => $minPrice, 'max' => $maxPrice, 'class' => 'form-control', 'required' => 'required', 'step'=>'0.01']) ?>
                            </div>
                        </td>
                        <td class='center'>
                            <?php $subTotal = $actual->price * $actual->quantity; ?>
                            <?= $actualCurrency->name . ' ' . number_format($subTotal) ?>
                        </td>
                    </tr>
                <?php } ?>
            <?php } ?>
            </tbody>
            <tbody>
        </table>
        <?= Html::input('hidden', 'id', $data->id) ?>
        <?= Html::submitButton('Simpan Revisi', ['class' => 'btn btn-primary']) ?>
    </form>
</div>

<script>
    $('#form-revision-detail').submit(function () {
        modalConfirm('Konfirmasi Tindakan', 'Apakah anda yakin data revisi sudah benar? Data tidak dapat diubah setelah disimpan!', function () {
            var data = getFormData('form-revision-detail');
            ajaxTransfer('po/modify/save/', data, '#modal-output');
        });
    });
</script>

views/po/modify/po-data.php
<div style='margin: 10px 0' class='form-horizontal col-lg-12 col-md-12 col-md-12'>
    <div class='form-group'>
        <label class='col-lg-3 col-md-3 control-label'>ID</label>
        <div class='col-lg-9 col-md-9 form-control-static'><?= $data->code ?></div>
    </div>
    <div class='form-group'>
        <label class='col-lg-3 col-md-3 control-label'>Amount Estimation</label>
        <div class='col-lg-9 col-md-9 form-control-static'><?= $data->display_amount_estimation ?></div>
    </div>
    <div class='form-group'>
        <label class='col-lg-3 col-md-3 control-label'>Amount Realization</label>
        <div class='col-lg-9 col-md-9 form-control-static'><?= $data->display_amount_realization ?></div>
    </div>
    <div class='form-group'>
        <label class='col-lg-3 col-md-3 control-label'>Term</label>
        <div class='col-lg-9 col-md-9 form-control-static'><?= $data->term->name ?></div>
    </div>
    <div class='form-group'>
        <label class='col-lg-3 col-md-3 control-label'>Franco</label>
        <div class='col-lg-9 col-md-9 form-control-static'><?= $data->franco->name ?></div>
    </div>
    <div class='form-group'>
        <label class='col-lg-3 col-md-3 control-label'>Supplier</label>
        <div class='col-lg-9 col-md-9 form-control-static'><?= $data->supplier->name ?></div>
    </div>
    <div class='form-group'>
        <label class='col-lg-3 col-md-3 control-label'>Est. Time Arrival</label>
        <div class='col-lg-9 col-md-9 form-control-static'><?= $data->estimated_time_arival ?></div>
    </div>
    <div class='form-group'>
        <label class='col-lg-3 col-md-3 control-label'>Actual Time Arrival</label>
        <div class='col-lg-9 col-md-9 form-control-static'><?= $data->is_closed ? date('d/m/Y H:i:s', strtotime($data->actual_time_arival)) : '-' ?></div>
    </div>
    <div class='form-group'>
        <label class='col-lg-3 col-md-3 control-label'>Down Payment</label>
        <div class='col-lg-9 col-md-9 form-control-static'><?= $data->display_down_payment_amount ?></div>
    </div>
    <div class='form-group'>
        <label class='col-lg-3 col-md-3 control-label'>Date Submit</label>
        <div class='col-lg-9 col-md-9 form-control-static'><?= $data->date_submit ?></div>
    </div>
    <div class='form-group' style='margin-bottom:10px;'>
        <label class='col-lg-3 col-md-3 control-label'>Comment</label>
        <div class='col-lg-9 col-md-9 form-control-static'><?= nl2br($data->comment) ?></div>
    </div>
</div>

views/po/modify/revision-detail.php
<table class='table table-bordered table-striped' id='table-revision-detail'>
    <thead>
    <tr>
        <th>PR Code</th>
        <th>Goods / Service</th>
        <th>Quantity</th>
        <th>Price</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($data->detail as $list) { ?>
        <tr class="nowrap">
            <td><?= $list->actual->poPrDetail->purchaseRequisition->code ?></td>
            <td><?= $list->actual->goodsService->name ?></td>
            <td class='center'><?= $list->quantity ?></td>
            <td class='center'><?= $list->display_price ?></td>
        </tr>
    <?php } ?>
    </tbody>
</table>